# code: language=ansible
# - name: Trilio for Kubernetes Smoketest
#  ansible.builtin.include_tasks: tvk_smoketest.yaml
#  when: tvk_smoketest | bool
#  tags: ['smoketest']

- name: Authentication to Kubernetes
  ansible.builtin.include_tasks: tvk_auth.yaml
  tags: ['always', 'auth']
  when: tvk_auth | bool

- name: Basic Trilio for Kubernetes Checks
  ansible.builtin.include_tasks: tvk_check.yaml
  tags: ['check']
  when: tvk_check | bool

- name: Searching for Backup Recommendations
  ansible.builtin.include_tasks: tvk_suggest.yaml
  tags: ['never', 'suggest', 'search', 'autoprotect']
  when: tvk_suggest | bool

- name: Trilio for Kubernetes Create Namespace
  ansible.builtin.include_tasks: tvk_create_ns.yaml
  tags: ['namespace', 'ns']
  when: tvk_create_namespace | bool

- name: Trilio for Kubernetes Deploy App
  ansible.builtin.include_tasks: tvk_deploy_app.yaml
  tags: ['never', 'deploy_app']
  when: tvk_deploy_demo_app | bool

- name: Trilio for Kubernetes Create Secret
  ansible.builtin.include_tasks: tvk_create_secret.yaml
  tags: ['secret']
  when: tvk_create_secret | bool

- name: Trilio for Kubernetes Create Target
  ansible.builtin.include_tasks: tvk_create_target.yaml
  tags: ['target']
  when: tvk_create_target | bool

- name: Trilio for Kubernetes Create Backup Plan
  ansible.builtin.include_tasks: tvk_create_backupplan.yaml
  tags: ['backupplan']
  when: tvk_create_backupplan | bool

- name: Trilio for Kubernetes Execute a Backup
  ansible.builtin.include_tasks: tvk_create_backup.yaml
  tags: ['backup']
  when: tvk_create_backup | bool

- name: Trilio for Kubernetes Perform Restore
  ansible.builtin.include_tasks: tvk_create_restore.yaml
  tags: ['never', 'restore']
  when: tvk_create_restore | bool

- name: Trilio for Kubernetes Smoketest
  ansible.builtin.include_tasks: tvk_smoketest.yaml
  tags: ['never', 'smoketest']
  when: tvk_smoketest | bool

- name: Cleanup Trilio For Kubernetes
  ansible.builtin.include_tasks: tvk_cleanup.yaml
  tags: ['never', 'smoketest_cleanup']
  when:
    - tvk_smoketest_cleanup | bool
    - tvk_smoketest | bool
    - tvk_restore_namespace is defined
  vars:
    tvk_namespace: "{{ tvk_restore_namespace }}"

- name: Cleanup Trilio For Kubernetes
  ansible.builtin.include_tasks: tvk_cleanup.yaml
  tags: ['never', 'smoketest_cleanup']
  when:
    - tvk_smoketest_cleanup | bool
    - tvk_smoketest | bool
