# code: language=ansible

# Set of tasks that will check a Kubernetes cluster for
# - Valid Trilio for Kubernetes License
# - CSI Drivers Present
# - VolumeSnapshot CRDs
#
# Authors: Kevin Jackson <kevin.jackson at trilio io>

# To Do
# Have Common Checks
# Have <distro> Specific Checks
#

- name: Basic Kubernetes Checks
  tags: ['check', 'smoketest']
  block:
    - name: Check for kubectl
      ansible.builtin.stat:
        path: /usr/local/bin/kubectl
      register: trilio_kubernetes_kubectl

- name: Basic OpenShift Checks
  tags: ['check', 'smoketest']
  when: trilio_kubernetes_distro == "openshift"
  block:
    - name: Check for oc
      ansible.builtin.stat:
        path: /usr/local/bin/oc
      register: trilio_kubernetes_oc

- name: Trilio for Kubernetes Prerequisite Checks
  tags: ['check', 'smoketest']
  block:
    - name: Checking for Trilio License
      kubernetes.core.k8s_info:
        api_version: triliovault.trilio.io/v1
        kind: License
        namespace: "{{ trilio_kubernetes_operator_namespace }}"
        validate_certs: false
      register: trilio_kubernetes_license
      when: trilio_kubernetes_distro == 'openshift'

    - name: Checking for CSI Drivers
      kubernetes.core.k8s_info:
        api_version: storage.k8s.io/v1
        kind: CSIDriver
        validate_certs: false
      register: trilio_kubernetes_csidrivers

    - name: Checking for CSI Drivers (kubeconfig)
      kubernetes.core.k8s_info:
        api_version: storage.k8s.io/v1
        kind: CSIDriver
        validate_certs: false
      register: trilio_kubernetes_csidrivers

    - name: Checking for VolumeSnapshot CRD
      kubernetes.core.k8s_info:
        api_version: apiextensions.k8s.io/v1
        kind: CustomResourceDefinition
        name: volumesnapshot.snapshot.storage.k8s.io
        validate_certs: false
      register: trilio_kubernetes_volumesnapshot

    - name: Checking for VolumeSnapshot CRD (kubeconfig)
      kubernetes.core.k8s_info:
        api_version: apiextensions.k8s.io/v1
        kind: CustomResourceDefinition
        name: volumesnapshot.snapshot.storage.k8s.io
        validate_certs: false
      register: trilio_kubernetes_volumesnapshot

    - name: Checking for VolumeSnapshotClass CRD
      kubernetes.core.k8s_info:
        api_version: apiextensions.k8s.io/v1
        kind: CustomResourceDefinition
        name: volumesnapshotclasses.snapshot.storage.k8s.io
        validate_certs: false
      register: trilio_kubernetes_volumesnapshotclasses

    - name: Checking for VolumeSnapshotClass CRD (kubeconfig)
      kubernetes.core.k8s_info:
        api_version: apiextensions.k8s.io/v1
        kind: CustomResourceDefinition
        name: volumesnapshotclasses.snapshot.storage.k8s.io
        validate_certs: false
      register: trilio_kubernetes_volumesnapshotclasses

    - name: Checking for VolumeSnapshotContent CRD
      kubernetes.core.k8s_info:
        api_version: apiextensions.k8s.io/v1
        kind: CustomResourceDefinition
        name: volumesnapshotclasses.snapshot.storage.k8s.io
        validate_certs: false
      register: trilio_kubernetes_volumesnapshotcontent

    - name: Checking for VolumeSnapshotContent CRD (kubeconfig)
      kubernetes.core.k8s_info:
        api_version: apiextensions.k8s.io/v1
        kind: CustomResourceDefinition
        name: volumesnapshotclasses.snapshot.storage.k8s.io
        validate_certs: false
      register: trilio_kubernetes_volumesnapshotcontent

  rescue:
    - name: Warn user on TVK errors
      ansible.builtin.debug:
        msg: 'Unable to perform TVK checks'
