# code: language=ansible

# Set of tasks for creating a Trilio for Kubernetes Backup
#
# Authors: Kevin Jackson <kevin.jackson at trilio io>

- name: Create Secret
  tags: ['secret']
  ansible.builtin.include_tasks: "trilio_kubernetes_create_secret_{{ trilio_kubernetes_auth_type }}.yaml"
  when: trilio_kubernetes_create_secret | bool
  vars:
    trilio_kubernetes_namespace_create: "{{ trilio_kubernetes_namespace }}"
