# code: language=ansible

# Set of tasks for creating a Trilio for Kubernetes Backup Plan in a namespace
# for describing what and where to backup
#
# Authors: Kevin Jackson <kevin.jackson at trilio io>

- name: Create Backup Plan
  ansible.builtin.include_tasks: "trilio_kubernetes_create_backupplan_kubeconfig.yaml"
  tags: ['backupplan', 'smoketest']
  when:
    - trilio_kubernetes_distro == 'kubernetes' or trilio_kubernetes_auth_type == 'external'
  vars:
    trilio_kubernetes_namespace_create: "{{ trilio_kubernetes_namespace }}"
    trilio_kubernetes_auth_results: "{{ trilio_kubernetes_openshift_auth_results }}"

- name: Create Backup Plan (OpenShift Auth)
  ansible.builtin.include_tasks: "trilio_kubernetes_create_backupplan_password.yaml"
  tags: ['backupplan', 'smoketest']
  when:
    - trilio_kubernetes_distro == 'openshift' and trilio_kubernetes_auth_type == 'password'
  vars:
    trilio_kubernetes_namespace_create: "{{ trilio_kubernetes_namespace }}"
    trilio_kubernetes_auth_results: "{{ trilio_kubernetes_openshift_auth_results }}"
