# code: language=ansible

# Set of tasks for creating performing a Trilio for Kubernetes Restore
#
# Authors: Kevin Jackson <kevin.jackson at trilio io>

- name: Perform Restore
  tags: ['restore', 'smoketest']
  block:
    - name: Create Restore Namespace
      ansible.builtin.include_tasks: "trilio_kubernetes_create_ns_kubeconfig.yaml"
      when: 
        - trilio_kubernetes_create_namespace | bool
        - trilio_kubernetes_distro == 'kubernetes' or trilio_kubernetes_auth_type == 'external'
      vars:
        trilio_kubernetes_namespace_create: "{{ trilio_kubernetes_restore_namespace }}"

    - name: Execute Continuous Restore Preparion Tasks
      ansible.builtin.include_tasks: "trilio_kubernetes_continuous_restore_{{ trilio_kubernetes_auth_type }}.yaml"
      when:
        - trilio_kubernetes_create_restore | bool
        - trilio_kubernetes_restore_type == "cr"

    - name: Execute Restore Tasks
      ansible.builtin.include_tasks: "trilio_kubernetes_create_restore_kubeconfig.yaml"
      when: 
        - trilio_kubernetes_create_restore | bool
        - trilio_kubernetes_distro == 'kubernetes' or trilio_kubernetes_auth_type == 'external'
