# code: language=ansible

# Set of tasks for creating a Trilio for Kubernetes Target in a namespace
# for storing backups (kubeconfig auth)
#
# Authors: Kevin Jackson <kevin.jackson at trilio io>

- name: Create Target
  tags: ['target', 'smoketest', 'migrate']
  when: trilio_kubernetes_target_type | lower == "s3"
  block:
    - name: Configure the target yaml
      ansible.builtin.template:
        src: templates/target.yaml.j2
        dest: /tmp/target.yaml
        mode: "0600"

    - name: Create the target in the namespace {{ trilio_kubernetes_namespace }}
      kubernetes.core.k8s:
        kind: Target
        state: present
        namespace: "{{ trilio_kubernetes_namespace }}"
        src: "/tmp/target.yaml"
        validate_certs: false
      register: trilio_kubernetes_target

- name: Show target output
  ansible.builtin.debug:
    var: trilio_kubernetes_target_available.stdout_lines
