# code: language=ansible

# Set of tasks for creating a Trilio for Kubernetes Target in a namespace
# for storing backups
#
# Authors: Kevin Jackson <kevin.jackson at trilio io>

- name: Create Namespace
  ansible.builtin.include_tasks: trilio_kubernetes_create_ns.yaml
  when: trilio_kubernetes_create_namespace | bool
  tags: ['namespace', 'smoketest', 'target', 'migrate']
  vars:
    trilio_kubernetes_namespace_create: "{{ trilio_kubernetes_namespace }}"

- name: Create Secret for S3
  ansible.builtin.include_tasks: "trilio_kubernetes_create_secret_{{ trilio_kubernetes_auth_type }}.yaml"
  tags: ['secret', 'smoketest']
  vars:
    trilio_kubernetes_namespace_create: "{{ trilio_kubernetes_namespace }}"

- name: Create Target
  ansible.builtin.include_tasks: "trilio_kubernetes_create_target_{{ trilio_kubernetes_auth_type }}.yaml"
  when: trilio_kubernetes_create_target | bool
  tags: ['target', 'smoketest']
  vars:
    trilio_kubernetes_namespace_create: "{{ trilio_kubernetes_namespace }}"
