# code: language=ansible

# Set of tasks for creating a Trilio for Kubernetes Backup Plan in a namespace
# for describing what and where to backup
#
# Authors: Kevin Jackson <kevin.jackson at trilio io>

- name: Create Backup Plan Tasks
  tags: ['backup', 'backupplan', 'smoketest', 'autoprotect']
  block:
    - name: Configure the backup plan in {{ trilio_kubernetes_namespace_create }}
      ansible.builtin.template:
        src: templates/backupplan.yaml.j2
        dest: /tmp/{{ trilio_kubernetes_backupplan_name }}-backupplan.yaml
        mode: "0600"

    # Create the specified backup plan in specifed namespace
    - name: Create the backup plan "{{ trilio_kubernetes_backupplan_name }}"
      kubernetes.core.k8s:
        kind: BackupPlan
        state: present
        namespace: "{{ trilio_kubernetes_namespace_create }}"
        src: "/tmp/{{ trilio_kubernetes_backupplan_name }}-backupplan.yaml"
        validate_certs: false
        wait: true
        wait_condition:
          type: Sync
          status: Completed
          reason: Sync Completed
      register: trilio_kubernetes_backupplan

#    - name: Wait for the backup plan to be created "{{ trilio_kubernetes_backupplan_name }}"
#      when: trilio_kubernetes_auth_type == "kubeconfig"
#      ansible.builtin.shell: >
#        kubectl get backupplans/"{{ trilio_kubernetes_backupplan_name }}" -n {{ trilio_kubernetes_namespace_create }}
#      environment:
#        KUBECONFIG: "{{ kubeconfig }}"
#      register: trilio_kubernetes_backupplan_available
#      retries: 5
#      delay: 5
#      until: trilio_kubernetes_backupplan_available.stdout.find("Available") != -1
#      ignore_errors: true

#    - name: Show backup plan created output
#      ansible.builtin.debug:
#        var: trilio_kubernetes_backupplan_available.stdout_lines
