# code: language=ansible

- name: Set namespace name
  ansible.builtin.set_fact:
    trilio_kubernetes_namespace_create: "{{ trilio_kubernetes_namespace }}"

- name: Create namespace {{ trilio_kubernetes_namespace_create }}
  tags: ['namespace', 'ns', 'smoketest', 'secret', 'target', 'deploy_app', 'backupplan']
  kubernetes.core.k8s:
    name: "{{ trilio_kubernetes_namespace_create }}"
    api_version: v1
    kind: Namespace
    validate_certs: false
    state: present
