# code: language=ansible

# Set of tasks for creating a Trilio for Kubernetes Backup
#
# Authors: Kevin Jackson <kevin.jackson at trilio io>

- name: Create Backup
  ansible.builtin.include_tasks: "tvk_create_backup_{{ k8s_auth_type }}.yaml"
  tags: ['backup', 'smoketest']
  when: tvk_create_backup | bool
