# code: language=ansible
# Set of tasks for creating a Trilio for Kubernetes Target in a namespace
# for storing backups (password auth)
#
# Authors: Kevin Jackson <kevin.jackson at trilio io>

- name: Create Target
  tags: ['target', 'smoketest', 'migrate']
  when: tvk_target_type | lower == "s3"
  block:
    - name: Configure the target yaml
      ansible.builtin.template:
        src: templates/target.yaml.j2
        dest: /tmp/target.yaml
        mode: 0600

    - name: Create the target in the namespace {{ tvk_namespace }}
      kubernetes.core.k8s:
        api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
        kind: Target
        state: present
        namespace: "{{ tvk_namespace }}"
        src: "/tmp/target.yaml"
        validate_certs: false
      register: target
      when: k8s_auth_type == 'password'

    - name: Wait for target to be created in the namespace {{ tvk_namespace }}
      ansible.builtin.shell: |
        oc login "{{ k8s_auth_api }}" --token="{{ openshift_auth_results.openshift_auth.api_key }}" --insecure-skip-tls-verify=true
        oc get targets/"{{ tvk_target_name }}" -n {{ tvk_namespace }}
      register: target_available
      retries: 5
      delay: 10
      until: target_available.stdout.find("Available") != -1
      ignore_errors: true
      when:
        - k8s_auth_type == "password"
        - k8s_distro == "openshift"

- name: Show target creation output
  ansible.builtin.debug:
    var: target_available.stdout_lines
