# code: language=ansible

# Set of tasks for creating a Trilio for Kubernetes Backup where auth is kubeconfig
#
# Authors: Kevin Jackson <kevin.jackson at trilio io>

- name: Execute Backup Tasks
  tags: ['backup', 'backupplan', 'smoketest', 'autoprotect']
  block:
    - name: Set restore name
      ansible.builtin.set_fact:
        tvk_backup_name: "{{ tvk_backupplan_name }}-{{ ansible_date_time.date }}-{{ ansible_date_time.epoch }}"

    - name: Configure the backup using {{ tvk_backupplan_name }}
      ansible.builtin.template:
        src: templates/backup.yaml.j2
        dest: /tmp/{{ tvk_backupplan_name }}-backup.yaml
        mode: 0600

    # Create the specified backup plan in specifed namespace
    - name: Execute the backup of {{ tvk_backup_name }}
      when: k8s_auth_type == "kubeconfig"
      kubernetes.core.k8s:
        kind: Backup
        state: present
        namespace: "{{ tvk_namespace }}"
        src: "/tmp/{{ tvk_backupplan_name }}-backup.yaml"
        validate_certs: false
      register: backup

    - name: Wait for {{ tvk_backup_name }}
      when: k8s_auth_type == "kubeconfig"
      ansible.builtin.shell: >
        kubectl get backups/{{ tvk_backupplan_name }}-{{ ansible_date_time.date }}-{{ ansible_date_time.epoch }} -n {{ tvk_namespace }}
      environment:
        KUBECONFIG: "{{ kubeconfig }}"
      register: backup_available
      retries: "{{ tvk_backup_polling_retries }}"
      delay: "{{ tvk_backup_polling_every_seconds }}"
      until: backup_available.stdout.find("Available") != -1
      ignore_errors: true

    - name: Show backup created output
      ansible.builtin.debug:
        var: backup_available.stdout_lines
