- name: Create {{ tvk_namespace }} namespace
  tags: ['namespace', 'ns', 'smoketest', 'target', 'deploy_app', 'backupplan']
  kubernetes.core.k8s:
    name: "{{ tvk_namespace }}" # defining the namespace
    api_version: v1
    kind: Namespace
    validate_certs: false
    state: present # State=present when you need to create new object
  when: k8s_auth_type == 'kubeconfig'
