# code: language=ansible

# Set of tasks for creating a Trilio for Kubernetes Backup
#
# Authors: Kevin Jackson <kevin.jackson at trilio io>

- name: Create Namespace
  tags: ['namespace', 'ns', 'smoketest']
  ansible.builtin.include_tasks: "tvk_create_ns_{{ k8s_auth_type }}.yaml"
  when: tvk_create_namespace | bool
