# code: language=ansible

# Set of tasks for creating a Trilio for Kubernetes Backup Plan in a namespace
# for describing what and where to backup
#
# Authors: Kevin Jackson <kevin.jackson at trilio io>

- name: Create Backup Plan Tasks
  tags: ['backup', 'backupplan', 'smoketest', 'autoprotect']
  block:
    - name: Configure the backup plan in {{ tvk_namespace }}
      ansible.builtin.template:
        src: templates/backupplan.yaml.j2
        dest: /tmp/{{ tvk_backupplan_name }}-backupplan.yaml
        mode: 0600

    # Create the specified backup plan in specifed namespace
    - name: Create the backup plan "{{ tvk_backupplan_name }}"
      kubernetes.core.k8s:
        kind: BackupPlan
        state: present
        namespace: "{{ tvk_namespace }}"
        src: "/tmp/{{ tvk_backupplan_name }}-backupplan.yaml"
        validate_certs: false
      register: backupplan
      when: k8s_auth_type == "kubeconfig"

    - name: Wait for the backup plan to be created "{{ tvk_backupplan_name }}"
      when: k8s_auth_type == "kubeconfig"
      ansible.builtin.shell: >
        kubectl get backupplans/"{{ tvk_backupplan_name }}" -n {{ tvk_namespace }}
      environment:
        KUBECONFIG: "{{ kubeconfig }}"
      register: backupplan_available
      retries: 5
      delay: 5
      until: backupplan_available.stdout.find("Available") != -1
      ignore_errors: true

    - name: Show backup plan created output
      ansible.builtin.debug:
        var: backupplan_available.stdout_lines
