# code: language=ansible

- name: Set namespace name
  ansible.builtin.set_fact:
    namespace: "{{ tvk_namespace }}"

- name: Create namespace {{ namespace }}
  tags: ['namespace', 'ns', 'smoketest', 'secret', 'target', 'deploy_app', 'backupplan']
  when: k8s_auth_type == 'kubeconfig'
  kubernetes.core.k8s:
    name: "{{ namespace }}"
    api_version: v1
    kind: Namespace
    validate_certs: false
    state: present
