# Set of tasks for creating a Trilio for Kubernetes Target in a namespace
# for storing backups (kubeconfig auth)
#
# Authors: Kevin Jackson <kevin.jackson at trilio io>

- name: Create Target
  block:
  - name: Configure the target yaml
    ansible.builtin.template:
      src: templates/target.yaml.j2
      dest: /tmp/target.yaml

  - name: Create the "{{ tvk_target_name }}" target in the {{ tvk_namespace }} namespace
    kubernetes.core.k8s:
      kind: Target
      state: present
      namespace: "{{ tvk_namespace }}"
      src: "/tmp/target.yaml"
      validate_certs: false
    register: target
    when: k8s_auth_type == 'kubeconfig'

  when: tvk_target_type | lower == "s3"
  tags: ['target', 'smoketest', 'migrate']

- name: Show target output
  ansible.builtin.debug:
    var: target_available.stdout_lines
