# code: language=ansible

# Set of tasks for creating a Trilio for Kubernetes Backup
#
# Authors: Kevin Jackson <kevin.jackson at trilio io>

- name: Create Secret
  tags: ['secret']
  ansible.builtin.include_tasks: "tvk_create_secret_{{ k8s_auth_type }}.yaml"
  when: tvk_create_secret | bool
