# code: language=ansible

- name: Set namespace name
  ansible.builtin.set_fact:
    namespace: "{{ tvk_namespace }}"

- name: Create namespace {{ namespace }}
  tags: ['namespace', 'ns', 'smoketest', 'secret', 'target', 'deploy_app', 'backupplan', 'restore']
  kubernetes.core.k8s:
    name: "{{ namespace }}"
    api_version: v1
    api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    kind: Namespace
    validate_certs: false
    state: present
  when: k8s_auth_type == 'password'

# For OpenShift we need to ensure the correct SCC is allowed
# Hack: ensure SCC is set, assumes kubeadmin username
- name: Set SCC Policy for namespace for OpenShift deployments
  tags: ['namespace', 'deploy_app', 'smoketest', 'restore']
  when:
    - k8s_auth_type == "password"
    - k8s_distro == "openshift"
    - k8s_username == "kubeadmin"
    - tvk_scc_policy_anyuid_to_ns | bool
  ansible.builtin.shell: |
    oc login "{{ k8s_auth_api }}" --token="{{ openshift_auth_results.openshift_auth.api_key }}" --insecure-skip-tls-verify=true
    oc adm policy add-scc-to-user anyuid -z default -n "{{ namespace }}"
  register: scc
